-- MySQL Script generated by MySQL Workbench
-- qua 28 nov 2018 20:39:00 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agenda-academica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda-academica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda-academica` DEFAULT CHARACTER SET utf8 ;
USE `agenda-academica` ;

-- -----------------------------------------------------
-- Table `agenda-academica`.`Dono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda-academica`.`Dono` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda-academica`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda-academica`.`Tarefa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` TIME NULL,
  `titulo` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(80) NULL,
  `dono_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tarefa_Dono1_idx` (`dono_id` ASC),
  CONSTRAINT `fk_Tarefa_Dono1`
    FOREIGN KEY (`dono_id`)
    REFERENCES `agenda-academica`.`Dono` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda-academica`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda-academica`.`Grupo` (
  `nome` VARCHAR(20) NOT NULL,
  `dono_id` INT NOT NULL,
  PRIMARY KEY (`dono_id`),
  INDEX `fk_Grupo_Dono1_idx` (`dono_id` ASC),
  CONSTRAINT `fk_Grupo_Dono1Grupo`
    FOREIGN KEY (`dono_id`)
    REFERENCES `agenda-academica`.`Dono` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda-academica`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda-academica`.`Usuario` (
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL UNIQUE,
  `senha` VARCHAR(45) NOT NULL,
  `dono_id` INT NOT NULL,
  PRIMARY KEY (`dono_id`),
  INDEX `fk_Usuario_Dono1_idx` (`dono_id` ASC),
  CONSTRAINT `fk_Usuario_Dono1`
    FOREIGN KEY (`dono_id`)
    REFERENCES `agenda-academica`.`Dono` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda-academica`.`Grupo_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda-academica`.`Grupo_has_Usuario` (
  `eh_admin` TINYINT(1) NOT NULL,
  `grupo_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`, `usuario_id`),
  INDEX `fk_Grupo_has_Usuario_Usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Grupo_has_Usuario_Grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `agenda-academica`.`Grupo` (`dono_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Usuario_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agenda-academica`.`Usuario` (`dono_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;Dono
